module CustomTypes.Cred exposing (Cred, decoder, encodeToken, username)

{-| ----------------------------------------------------------------------------
    Simple `Cred`entials with `Username` custom type
    ============================================================================
    > ⚠️ `Cred` is an OPAQUE TYPE. See the book "Learn Type-driven development"
    > @ https://github.com/badlydrawnrob/learn-type-driven/

    Opaque types must expose the public functions users need in order to create
    and transform it. See also `CustomTypes.Username` which this module requires.


    Important
    ---------
    > Don't fall into the trap of making too many "getters" or "setters". If you
    > have lots of fields with the same type, consider a record instead.

    The point of an Opaque Type is to hide the implementation details. We only
    expose what's absolutely essential (such as the username).


    What I learned
    --------------
    1. `Cred` can only be created internally by this module.
    2. `Cred` can only be generated by an API endpoint and decoded from `json`.
    3. `Cred` could've been a record, but it isn't necessary for so few values.
        - It's also easier to update than a nested record!
        - A record however is slightly easier to deconstruct.
    4. Other parts of the program can import `CustomTypes.Cred` to create and
       access parts of the `Cred` type, such as the `Username` value.
        - `Username` also has `toString` function you can use.


    What I learned
    --------------
    1. To access the `username` function, we could import as
       `Cred` (the module) and use `Cred.username` to get the function. We can
       then pass `username` the `Cred` (decoded custom type) value.
    2. Using a record isn't necessary for so few values
    3. But a record can be deconstructed (Cred { token }) without `_`, which
       makes life a little easier.
    4. Don't fall into the trap of making too many "getters" or "setters".
        - The whole point of Opaque Types is to hide implementation detail.
        - Only expose what's absolutely essential (such as `Username`)

-}

import Json.Encode as Encode exposing (Value)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (required)
import CustomTypes.Username as Username exposing (Username)

type Cred
    = Cred Username String

{- See `Username` module -}
username : Cred -> Username
username (Cred user _) =
    user


-- Decoders --------------------------------------------------------------------

decoder : Decoder Cred
decoder =
    Decode.succeed Cred
        |> required "username" Username.decoder
        |> required "token" Decode.string

-- Encoders --------------------------------------------------------------------

encodeToken : Cred -> Value
encodeToken (Cred _ token) =
    Encode.string token
