module Http.Photo exposing (..)

{-| A simple photo app

> Example of when we'd need to know about `Status a` in the update function, and
> when it's safe to ignore it (and let `view` handle it).

1. Don't make life complicated. Simplify all the things
2. Our data might be slow so we account for that too
3. Never nest models or messages if you can avoid it!
4. When might we not need to worry about impossible states?
5. @ elm-explorations/markdown / @ pablohirafuji/elm-markdown

How can Ai be used to speed up development?
See the document on Photo and pinging the server.
Use the simplified url setup from @lydell (or the ports version)

`Status.map` or `Status.unpack`?
`LoadingSlowly` for 1x images or text-only.
`Photo` as an opaque type? (generated by server)

See `Message.NarrowTypes` for the only time we might need to nest a message.
Otherwise flat messages if it's something like `PizzaBase` and `Main` holds the
`Base PizzaBase` type. See Elm Spa for the nested `Form` example (use rarely).

## API

For now we don't need a M2M relationship, but you should normally use it instead
of arrays (as they constantly need to be updated). You _might_ want to give the
user the opportunity to add their own custom tags, but I'm not sure the best way
to handle that (how does Goodreads handle it?). See also ThingDB.

## Arrays -vs- Many-to-Many

> Re-watch "ThingDB" and normalisation for M2M

-}
